#!/usr/bin/env bash

install_or_update_brew() {
  if command -v brew 2>/dev/null; then
    brew update
  else
    echo "Installing Brew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

setup_fish() {
  if  [[ $(echo $SHELL) == *fish ]]; then
    echo "Fish installed and set as default"
  else

    if [[$(cat /etc/shells | grep fish | wc -l) == 1]]
    
  fi
}

install_or_update_brew
brew bundle --file=$(git rev-parse --show-toplevel)/Brewfile
setup_fish
